<?php

/**
 * @file
 * Preprocess functions for Knight Hennessy.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function khs_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function khs_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'khs_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function khs_subtheme_preprocess_ds_entity_view(&$variables) {
  // if not running on a paragraph, exit out.
  if (!isset($variables['content']['#paragraph'])) {
    return;
  }

  $paragraph = $variables['content']['#paragraph'];

  // Process Banners
  if ($paragraph->bundle() == 'stanford_banner') {
    khs_subtheme_preprocess_banner($variables);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function khs_subtheme_preprocess_paragraph__stanford_wysiwyg(array &$variables): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = &$variables['paragraph'];
  $existing_classes = $variables['attributes']['class'] ?? [];
  $extra_classes = [
    $paragraph->getBehaviorSetting('react_paragraphs:wysiwyg_style', 'wysiwyg_style', 'khs--default'),
  ];
  $variables['attributes']['class'] = array_merge($existing_classes, $extra_classes);
}

/**
 * Implements hook_preprocess_banner().
 */
function khs_subtheme_preprocess_banner(&$variables) {

  $paragraph = $variables['content']['#paragraph'];

  // Add button color style class to card wrapper.
  $variables['attributes']['class'][] = $paragraph->getBehaviorSetting('react_paragraphs:banner_variant_info', 'banner_style', 'khs-wrapper--banner-default');
}
